// export const products = [
//     {
//         id: 1,
//         name: 'Buzo Nike Blanco',
//         price: 4000,
//         stock: 6,
//         img: 'https://i.pinimg.com/originals/67/ae/77/67ae77a75174822609949601775a9186.jpg',
//         category: { id: 1, title: "buzos" },
//         description: "Buzo Nike Cap Slim. 100% algodón",
//     },
//     {
//         id: 2,
//         name: 'Campera Under Armour Gris',
//         price: 1100,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/cf/6b/98/cf6b98f7f3fa6498a5b8c54a84f710c8.jpg',
//         category: { id: 2, title: "camperas" },
//         description: "Campera New Cap Under Armour. Lycra Elastizada ",
        
//     },
//     {
//         id: 3,
//         name: 'Campera Under Armour Negra',
//         price: 2900,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/1c/db/93/1cdb93bd781e1486118ea1c4d462d791.jpg',
//         category: { id: 2, title: "camperas" },
//         description: "Campera New Cap Toral Black Under Armour. Lycra Elastizada ",

//     },
//     {
//         id: 4,
//         name: 'Chomba Nike Mostaza',
//         price: 1000,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/61/70/60/617060e83fe89a3ef99a1932480448d1.jpg',
//         category: { id: 3, title: "chombas" },
//         description: "Chomba Nike Color Mostaza. 100% algodón.",
        
//     },
//     {
//         id: 5,
//         name: 'Chomba Nike Gris',
//         price: 1300,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/b7/8e/6f/b78e6fad7423b725363cdf7afb98e335.jpg',
//         category: { id: 3, title: "chombas" },
//         description: "Chomba Nike Color Mostaza. 100% algodón.",
//     },
//     {
//         id: 6,
//         name: 'Conjunto con Calza Nike Negro',
//         price: 1300,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/cc/47/c0/cc47c0a07924ddc076398de921909166.jpg',
//         category: { id: 4, title: "conjuntos" },
//         description: "Conjunto de Top y Short Nike Color Negro",
//     },
//     {
//         id: 7,
//         name: 'Conjunto Under Armour Negro',
//         price: 1300,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/84/44/b6/8444b67b6cc49885019d32dc3ea6ddc1.jpg',
//         category: { id: 4, title: "conjuntos" },
//         description: "Conjunto de Top y Short Under Armour Color Negro",
//     },
//     {
//         id: 8,
//         name: 'Jogging Adidas Azul',
//         price: 1300,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/c2/0d/f7/c20df7d814b77eb536a18f880d24b556.jpg',
//         category: { id: 5, title: "joggings" },
//     },
//     {
//         id: 9,
//         name: 'Jogging Adidas Negro',
//         price: 1300,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/4b/e3/56/4be356cf094dc6b89b05da60dfaaa762.jpg',
//         category: { id: 5, title: "joggings" },
//         description: "Jogging Adidas Retro. Microfibra Soft con Lycra",
//     },
//     {
//         id: 10,
//         name: 'Remera Nike Air Roja',
//         price: 1300,
//         stock: 10,
//         img: 'https://i.pinimg.com/originals/da/c3/ed/dac3edd9648356b3ea8a591ebb3f1487.jpg',
//         category: { id: 6, title: "remeras" },
//         description: "Remera Nike Air Color Roja. 100% algodón",
        
//     },
// ]